/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopetshop;

/**
 *
 * @author enzoe
 */
public class TelaServicos extends javax.swing.JFrame {

    /**
     * Creates new form TelaServicos
     */
    
    TelaPrincipal principal;
    
    public TelaServicos() {
        initComponents();
    }
    
    public TelaServicos(TelaPrincipal principal) {
        initComponents();
        this.principal = principal; 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        preco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TosarCheck = new javax.swing.JCheckBox();
        DeliveryCheck = new javax.swing.JCheckBox();
        TreinarCheck = new javax.swing.JCheckBox();
        BanhoCheck = new javax.swing.JCheckBox();
        VacinacaoCheck = new javax.swing.JCheckBox();
        ExameCheck = new javax.swing.JCheckBox();
        preco1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviços");
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Serviços:");

        btConfirmar.setText("Confirmar");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        preco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        preco.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Preço:");

        TosarCheck.setText("Tosar");
        TosarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TosarCheckActionPerformed(evt);
            }
        });

        DeliveryCheck.setText("Delivery");
        DeliveryCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryCheckActionPerformed(evt);
            }
        });

        TreinarCheck.setText("Treinar");
        TreinarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreinarCheckActionPerformed(evt);
            }
        });

        BanhoCheck.setText("Banho");
        BanhoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanhoCheckActionPerformed(evt);
            }
        });

        VacinacaoCheck.setText("Vacinação");
        VacinacaoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacinacaoCheckActionPerformed(evt);
            }
        });

        ExameCheck.setText("Exame");
        ExameCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExameCheckActionPerformed(evt);
            }
        });

        preco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        preco1.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(btConfirmar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TosarCheck)
                                    .addComponent(DeliveryCheck)
                                    .addComponent(TreinarCheck))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BanhoCheck)
                                    .addComponent(VacinacaoCheck)
                                    .addComponent(ExameCheck)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(preco1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TosarCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeliveryCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TreinarCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BanhoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VacinacaoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExameCheck)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preco1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btCancelar)
                    .addComponent(btConfirmar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       principal.setEnabled(true);
       principal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        principal.setEnabled(true);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void TosarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TosarCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (TosarCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 35));
        } else  if (TosarCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 35));
        }
    }//GEN-LAST:event_TosarCheckActionPerformed

    private void BanhoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanhoCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (BanhoCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 30));
        } else if (BanhoCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 30));
        }
    }//GEN-LAST:event_BanhoCheckActionPerformed

    private void DeliveryCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (DeliveryCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 25));
        } else if (DeliveryCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 25));
        }
    }//GEN-LAST:event_DeliveryCheckActionPerformed

    private void TreinarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreinarCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (TreinarCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 125));
        } else if (TreinarCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 125));
        }
    }//GEN-LAST:event_TreinarCheckActionPerformed

    private void VacinacaoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacinacaoCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (VacinacaoCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 75));
        } else if (VacinacaoCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 75));
        }
    }//GEN-LAST:event_VacinacaoCheckActionPerformed

    private void ExameCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExameCheckActionPerformed
        int precoAtual = Integer.parseInt(preco.getText());
        if (ExameCheck.isSelected()) {
            preco.setText(String.valueOf(precoAtual + 50));
        } else if (ExameCheck.isSelected() == false){
            preco.setText(String.valueOf(precoAtual - 50));
        }
        
    }//GEN-LAST:event_ExameCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaServicos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BanhoCheck;
    private javax.swing.JCheckBox DeliveryCheck;
    private javax.swing.JCheckBox ExameCheck;
    private javax.swing.JCheckBox TosarCheck;
    private javax.swing.JCheckBox TreinarCheck;
    private javax.swing.JCheckBox VacinacaoCheck;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel preco1;
    // End of variables declaration//GEN-END:variables
}
